### ISSUE TITLE
Overhaul dataset loading

### ISSUE THREAD

**Issue by domoritz** [vega/vega-lite-ui#77]
Support drag and drop, multiple myria instances, loading from URL, ...

Covers #74, #76, #72, #68

**Comment by kadamwhite** [comment]
Summary of the issues this rolls up:

- [ ] Re-tool dataset dialog to provide more options with a better UI (was #72, #74)
- [ ] Handle drag-and-drop uploading of data files (was #68)
- [ ] Include ability to switch Myria instance in dataset dialog (was #76)

From a process standpoint I would have kept these as separate issues, because they seem to build upon each other; but, for now, I am focusing on the re-tool dialog task.

**Comment by kadamwhite** [comment]
Copying @vlandham's proposed wireframe from #74:

![image](https://cloud.githubusercontent.com/assets/442115/10112955/9fc9a4e0-63ad-11e5-997e-fccab4a829e3.png)

**Comment by kadamwhite** [comment]
@domoritz I think I'm going to need more background on what Myria is and how it works before I can handle that check-mark on this issue. Are there any resources you know of that I could look at?

**Comment by domoritz** [comment]
It's a distributed database systems I've worked on and we wanted to show how polestar/voyager could integrate with other tools. Read more about myria at http://myria.cs.washington.edu/

**Comment by kadamwhite** [comment]
@domoritz Do you have examples of other instances, that I could test against?

**Comment by domoritz** [comment]
The demo instance is the only instance that is publicly available. One issue with it is that it doesn't support ssl at this point.

**Comment by kadamwhite** [comment]
Thanks

**Comment by kadamwhite** [comment]
Punting on Myria, didn't end up having time to get this in: I'm closing the rest of the issue since all other to-do items seem to be improved, and Myria issue was moved to a new ticker #121
